name: pyrfume
channels:
  - defaults
dependencies:
  - dask
  - ipython
  - ipywidgets
  - matplotlib
  - numpy
  - pandas
  - plotly
  - python>=3.4
  - conda-forge::rdkit
  - scikit-learn
  - scipy
  - sympy
  - pip:
    - missingpy
    - mordred
    - pubchempy
    - quantities
    - rickpy
